version: '2'

volumes:
   prometheus_data: {}
   grafana_data : {}

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
     - ./config:/etc/prometheus
     - prometheus_data:/prometheus
    ports:
     - 9090:9090
    command: 
     - '--config.file=/etc/prometheus/prometheus_sdk.yml'
     - '--storage.tsdb.path=/prometheus'
     - '--web.console.libraries=/usr/share/prometheus/console_libraries'
     - '--web.console.templates=/usr/share/prometheus/consoles'
    links:
     - cadvisor
     - metrics-gateway

  grafana:
    image: grafana/grafana:5.1.0
    container_name: grafana
    ports:
      - 3000:3000
    user: "104"
    links:
      - prometheus
  
  metrics-gateway :
    image : prom/pushgateway
    ports :
      - 9091:9091

  cadvisor:
   image: google/cadvisor:canary
   container_name: cadvisor
   volumes:
    - "/:/rootfs:ro"
    - "/var/run:/var/run:rw"
    - "/sys:/sys:ro"
    - "/var/lib/docker/:/var/lib/docker:ro"
   ports:
    - "8090:8080"
