version: '2' 


services:

    prometheus:
        restart: always
        image: prom/prometheus
        container_name: prometheus
        volumes:
            - './prometheus.yml:/etc/prometheus/prometheus.yml'
            # - './faucet.rules.yml:/etc/prometheus/faucet.rules.yml'
            # - './etc/prometheus/faucet.rules.yml:/etc/prometheus/faucet.rules.yml'
        ports:
            - 9090:9090
        links:
            - cadvisor
            #- faucet
            #- gauge

    grafana:
        restart: always
        image: 'grafana/grafana:5.4.0'
        container_name: grafana
        user: 'root'
        ports:
            - '3000:3000'
        volumes:
            - './opt/grafana:/var/lib/grafana'
        links:
            #- influxdb
            - prometheus

    cadvisor:
        image: google/cadvisor:canary
        container_name: cadvisor
        volumes:
            - "/:/rootfs:ro"
            - "/var/run:/var/run:rw"
            - "/sys:/sys:ro"
            - "/var/lib/docker/:/var/lib/docker:ro"
        ports:
            - "8090:8080"







